// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGNVQZle4mFZPsVcUQ1kHXz1WY8gGL3Y',
    appId: '1:94969296402:web:2d0ab9153a7ccdce218acb',
    messagingSenderId: '94969296402',
    projectId: 'datafirebase-965fe',
    authDomain: 'datafirebase-965fe.firebaseapp.com',
    storageBucket: 'datafirebase-965fe.appspot.com',
    measurementId: 'G-CEB40G3W8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-ufUNnkF_9r9_CW3TBxKzP6CZOlBkg0',
    appId: '1:94969296402:android:85a4256e196f443d218acb',
    messagingSenderId: '94969296402',
    projectId: 'datafirebase-965fe',
    storageBucket: 'datafirebase-965fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EJEukG75YbfEnWjfEMccGQ6XRl-jHPg',
    appId: '1:94969296402:ios:861a4b017992384b218acb',
    messagingSenderId: '94969296402',
    projectId: 'datafirebase-965fe',
    storageBucket: 'datafirebase-965fe.appspot.com',
    iosBundleId: 'com.example.cutiPegawai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EJEukG75YbfEnWjfEMccGQ6XRl-jHPg',
    appId: '1:94969296402:ios:7cb2e5b31d6ab434218acb',
    messagingSenderId: '94969296402',
    projectId: 'datafirebase-965fe',
    storageBucket: 'datafirebase-965fe.appspot.com',
    iosBundleId: 'com.example.cutiPegawai.RunnerTests',
  );
}
