// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0ZVu_KwPdQ07f9qjiovU1_608lFzATg',
    appId: '1:953417020541:web:aadb2cd11961c67a096d14',
    messagingSenderId: '953417020541',
    projectId: 'fir-task-21e74',
    authDomain: 'fir-task-21e74.firebaseapp.com',
    storageBucket: 'fir-task-21e74.appspot.com',
    measurementId: 'G-9H46ZYP635',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUIKQSM2ZLci95DNRXsayZPTSspgjucM',
    appId: '1:953417020541:android:c1d88b11453bdebd096d14',
    messagingSenderId: '953417020541',
    projectId: 'fir-task-21e74',
    storageBucket: 'fir-task-21e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcRgCJpC388fUl2J10OBSRQ9vVygGhWY',
    appId: '1:953417020541:ios:2f7b8214fd09bc7f096d14',
    messagingSenderId: '953417020541',
    projectId: 'fir-task-21e74',
    storageBucket: 'fir-task-21e74.appspot.com',
    iosBundleId: 'com.example.suratApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATcRgCJpC388fUl2J10OBSRQ9vVygGhWY',
    appId: '1:953417020541:ios:7fdbae5f7aa5eb12096d14',
    messagingSenderId: '953417020541',
    projectId: 'fir-task-21e74',
    storageBucket: 'fir-task-21e74.appspot.com',
    iosBundleId: 'com.example.suratApp.RunnerTests',
  );
}
